### ISSUE TITLE
error_received() now does nothing in asyncudp 0.7.0

### ISSUE THREAD

**Issue by eerimoq** [rmb122/xss-receiver#10]
This is no longer needed. Fixed upstream in https://github.com/eerimoq/asyncudp/commit/c6d404f8951c1dae3a77ec2370f3019976154930.

https://github.com/rmb122/xss-receiver/blob/ceeed65551b4d10e90d85a8fbac6860d80a2dac2/xss_receiver/utils.py#L253

**Comment by rmb122** [comment]
Thanks for your notice 😃, fixed in https://github.com/rmb122/xss-receiver/commit/a47f21adc5cd937acd50bb5f4621539defddb5d3.
