### ISSUE TITLE
请问这是什么情况

### ISSUE THREAD

**Issue by LinLuosheng** [rmb122/xss-receiver#11]
![image](https://user-images.githubusercontent.com/50785665/208279353-2a17b2d5-2ee6-4ed7-b04f-2b2cbf5c81e2.png)
请问这是什么情况

**Comment by rmb122** [comment]
项目没有在 Windows 上做过测试, 看起来像是 Windows 下多进程的问题 = =. 建议用 Linux, Windows Docker 或者 WSL 试试.

**Comment by LinLuosheng** [comment]
好的吧

**Comment by lc-bitsec** [comment]
app.py代码中把from xss_receiver import app, system_config 这一行放进 if __name__ == "__main__": 内部执行就可以了
