### ISSUE TITLE
xss-receiver-master-app 这个image一直Restarting

### ISSUE THREAD

**Issue by LTWtao** [rmb122/xss-receiver#12]
xss-receiver-master-app 这个image一直Restarting，看了日志报错“ImportError: cannot import name 'CLOSED' from 'websockets.connection' (/usr/local/lib/python3.10/site-packages/websockets/connection.py)”，是不是pull的源出问题了？

**Comment by rmb122** [comment]
依赖的问题, 可以在 sanic 的 issue 里找到, https://github.com/sanic-org/sanic/issues/2733

**Comment by rmb122** [comment]
git pull 之后重新 build 镜像应该就好了 `docker-compose build`

**Comment by LTWtao** [comment]
可以了，谢谢师傅



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月17日(周三) 下午4:52
收件人: ***@***.***&gt;;
抄送: "Tao ***@***.******@***.***&gt;;
主题: Re: [rmb122/xss-receiver] xss-receiver-master-app 这个image一直Restarting (Issue #12)




 
git pull 之后重新 build 镜像应该就好了 docker-compose build
