### ISSUE TITLE
密码提示错误

### ISSUE THREAD

**Issue by dd404x** [rmb122/xss-receiver#3]
![image](https://user-images.githubusercontent.com/19923974/105152584-595a6e80-5b42-11eb-93fc-162ca9c9bb84.png)

**Comment by rmb122** [comment]
docker 里面有个 change_pass.py, docker exec 进去可以更改密码

**Comment by dd404x** [comment]
![image](https://user-images.githubusercontent.com/19923974/105463779-871eef00-5ccb-11eb-8f6c-fc91dd4fbec4.png)
好像不行，还是报密码错误

**Comment by dd404x** [comment]
![image](https://user-images.githubusercontent.com/19923974/105463924-b7668d80-5ccb-11eb-94e3-a3744e9de91a.png)
这么改的

**Comment by dd404x** [comment]
怎么修改可以不使用密码登录，直接进入后台

**Comment by rmb122** [comment]
判断密码的逻辑在这里 https://github.com/rmb122/xss-receiver/blob/master/xss_receiver/controllers/AuthController.py#L21, 你可以改成

```py
@auth_controller.route("/login", methods=['POST'])
def login():
    if isinstance(request.json, dict):
        password = request.json.get('password', None)
        username = request.json.get('username', None)

        if isinstance(username, str) and isinstance(password, str) and True:
            token = sign_token().decode()
            system_log = SystemLog(log_content=f'Admin login with username [{username}]')
            db.session.add(system_log)
            db.session.commit()
            return jsonify(Response.success('登录成功', token))
        else:
            return jsonify(Response.failed('用户名或密码错误'))
    else:
        return jsonify(Response.invalid('无效请求'))
```
就可以不需要密码了

**Comment by rmb122** [comment]
改完密码需要重启一下 docker 才会生效, 忘了说了...

**Comment by dd404x** [comment]
![image](https://user-images.githubusercontent.com/19923974/105570581-4f747d80-5d85-11eb-820e-b3085ddfbee6.png)
![image](https://user-images.githubusercontent.com/19923974/105570595-5e5b3000-5d85-11eb-8f16-b37326abf102.png)
![image](https://user-images.githubusercontent.com/19923974/105570605-64e9a780-5d85-11eb-9209-1a0b386f7a1b.png)不知道什么原因，我已经更改代码逻辑而且重启了，但还是报错账号或密码错误， 按理说也应该 报错用户名或密码错误呀。我甚至删除了镜像重新构建也还是这个错误

**Comment by rmb122** [comment]
我本地复现了下, 现在已经修复了这个 bug. 原因是上游 PyJWT 更改了 api 返回的类型.  
https://github.com/jpadilla/pyjwt/commit/5d33b041f2aeccc653436958c08187f1bd538d94
在之前 sign token 返回的是 bytes 类型, 最近的一次更新直接 str 了... 所以导致中间报错了, 所以把 .decode() 删掉就好了

**Comment by dd404x** [comment]
好的，谢谢师傅
