### ISSUE TITLE
在创建规则测试的时候,ip一直是Header not found，望解答

### ISSUE THREAD

**Issue by niubility6** [rmb122/xss-receiver#4]
在创建规则测试的时候,ip一直是Header not found，望解答

**Comment by rmb122** [comment]
在反向代理后面的话需要通过 X-Real-IP Header 将真实 IP 发给后端
如果是直接部署的话需要确认下配置文件中的 BEHIND_PROXY 是否为 False

**Comment by niubility6** [comment]
> 

谢谢，已经可以了，还有一个小问题问一下大佬，发件邮箱在哪里配置

**Comment by rmb122** [comment]
Docker 部署的话是在 /app/xss_receiver/Config.py 里面

**Comment by niubility6** [comment]
> Docker 部署的话是在 /app/xss_receiver/Config.py 里面

好的谢谢，为啥我获取到的一直是172.18.0.1，是不能套cdn吗？

**Comment by rmb122** [comment]
需要配置正确的 X-Real-IP 头, 可以参考 https://github.com/rmb122/xss-receiver/blob/master/docker/reverse_proxy.conf

**Comment by niubility6** [comment]
> 需要配置正确的 X-Real-IP 头, 可以参考 https://github.com/rmb122/xss-receiver/blob/master/docker/reverse_proxy.conf

我把Behind_proxy改成了false，昨天是正常的，今天突然这样了

**Comment by niubility6** [comment]
换了一台服务器就搭建不起来了，日志如下
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 16)
spawned uWSGI worker 1 (pid: 28, cores: 1)
spawned uWSGI worker 2 (pid: 29, cores: 1)
cache sweeper thread enabled
2022-01-18 08:05:05,535 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by rmb122** [comment]
> > 需要配置正确的 X-Real-IP 头, 可以参考 https://github.com/rmb122/xss-receiver/blob/master/docker/reverse_proxy.conf
> 
> 我把Behind_proxy改成了false，昨天是正常的，今天突然这样了

Docker 部署需要开 Behind_proxy, 不然拿到的是 Docker 网络里面主机的地址



> 换了一台服务器就搭建不起来了，日志如下 sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: https://sqlalche.me/e/14/e3q8) unable to load app 0 (mountpoint='') (callable not found or import error) *** no app loaded. going in full dynamic mode *** *** uWSGI is running in multiple interpreter mode *** spawned uWSGI master process (pid: 16) spawned uWSGI worker 1 (pid: 28, cores: 1) spawned uWSGI worker 2 (pid: 29, cores: 1) cache sweeper thread enabled 2022-01-18 08:05:05,535 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

是当前文件夹权限不够写 sqlite 数据库, 不用 Docker 部署的话可以改一下权限或者用数据库

另外这个月有会大更新, 可以等等更新再部署 233

**Comment by niubility6** [comment]
> > > 需要配置正确的 X-Real-IP 头, 可以参考 https://github.com/rmb122/xss-receiver/blob/master/docker/reverse_proxy.conf
> > 
> > 
> > 我把Behind_proxy改成了false，昨天是正常的，今天突然这样了
> 
> Docker 部署需要开 Behind_proxy, 不然拿到的是 Docker 网络里面主机的地址
> 
> > 换了一台服务器就搭建不起来了，日志如下 sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: https://sqlalche.me/e/14/e3q8) unable to load app 0 (mountpoint='') (callable not found or import error) *** no app loaded. going in full dynamic mode *** *** uWSGI is running in multiple interpreter mode *** spawned uWSGI master process (pid: 16) spawned uWSGI worker 1 (pid: 28, cores: 1) spawned uWSGI worker 2 (pid: 29, cores: 1) cache sweeper thread enabled 2022-01-18 08:05:05,535 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> 
> 是当前文件夹权限不够写 sqlite 数据库, 不用 Docker 部署的话可以改一下权限或者用数据库
> 
> 另外这个月有会大更新, 可以等等更新再部署 233

--- no python application found, check your startup logs for errors ---
也会报这个错误 emmm

**Comment by niubility6** [comment]
> > > > 需要配置正确的 X-Real-IP 头, 可以参考 https://github.com/rmb122/xss-receiver/blob/master/docker/reverse_proxy.conf
> > > 
> > > 
> > > 我把Behind_proxy改成了false，昨天是正常的，今天突然这样了
> > 
> > 
> > Docker 部署需要开 Behind_proxy, 不然拿到的是 Docker 网络里面主机的地址
> > > 换了一台服务器就搭建不起来了，日志如下 sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: https://sqlalche.me/e/14/e3q8) unable to load app 0 (mountpoint='') (callable not found or import error) *** no app loaded. going in full dynamic mode *** *** uWSGI is running in multiple interpreter mode *** spawned uWSGI master process (pid: 16) spawned uWSGI worker 1 (pid: 28, cores: 1) spawned uWSGI worker 2 (pid: 29, cores: 1) cache sweeper thread enabled 2022-01-18 08:05:05,535 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> > 
> > 
> > 是当前文件夹权限不够写 sqlite 数据库, 不用 Docker 部署的话可以改一下权限或者用数据库
> > 另外这个月有会大更新, 可以等等更新再部署 233
> 
> --- no python application found, check your startup logs for errors --- 也会报这个错误 emmm

方便加个qq吗？大佬

**Comment by rmb122** [comment]
> > > > 需要配置正确的 X-Real-IP 头, 可以参考 https://github.com/rmb122/xss-receiver/blob/master/docker/reverse_proxy.conf
> > > 
> > > 
> > > 我把Behind_proxy改成了false，昨天是正常的，今天突然这样了
> > 
> > 
> > Docker 部署需要开 Behind_proxy, 不然拿到的是 Docker 网络里面主机的地址
> > > 换了一台服务器就搭建不起来了，日志如下 sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: https://sqlalche.me/e/14/e3q8) unable to load app 0 (mountpoint='') (callable not found or import error) *** no app loaded. going in full dynamic mode *** *** uWSGI is running in multiple interpreter mode *** spawned uWSGI master process (pid: 16) spawned uWSGI worker 1 (pid: 28, cores: 1) spawned uWSGI worker 2 (pid: 29, cores: 1) cache sweeper thread enabled 2022-01-18 08:05:05,535 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> > 
> > 
> > 是当前文件夹权限不够写 sqlite 数据库, 不用 Docker 部署的话可以改一下权限或者用数据库
> > 另外这个月有会大更新, 可以等等更新再部署 233
> 
> --- no python application found, check your startup logs for errors --- 也会报这个错误 emmm

最好还是用 Docker 部署把, 不然配置还是挺麻烦的 2333, QQ 就不用加了, 有问题可以继续在这个 issue 下讨论

**Comment by niubility6** [comment]
> 2333

我就是用的docker部署的，昨天搭建正常，今天换了个服务器就一直不行

**Comment by rmb122** [comment]
你是没有 dockerc-composer 直接用 Docker build 起的么, 用 docker-compose 看看

**Comment by niubility6** [comment]
> 你是没有 dockerc-composer 直接用 Docker build 起的么, 用 docker-compose 看看

用的是docker-compose现在ok了    但是header里面 x-real-ip显示的和client_ip一样 正常吗？之前好像是显示目标服务器ip

**Comment by rmb122** [comment]
> > 你是没有 dockerc-composer 直接用 Docker build 起的么, 用 docker-compose 看看
> 
> 用的是docker-compose现在ok了 但是header里面 x-real-ip显示的和client_ip一样 正常吗？之前好像是显示目标服务器ip

client_ip 就是从 x-real-ip 里面获取的, 一样是正常的
