### ISSUE TITLE
报错，启动不起来新版

### ISSUE THREAD

**Issue by niubility6** [rmb122/xss-receiver#6]
mkdir: cannot create directory ‘/app/uploads’: File exists
[*] Waiting mysql start...
Traceback (most recent call last):
  File "/app/app.py", line 1, in 
    from xss_receiver import app
  File "/app/xss_receiver/__init__.py", line 1, in 
    import sanic
ModuleNotFoundError: No module named 'sanic'

**Comment by rmb122** [comment]
`docker-compose build` 重新构建一下, 另外更新后之前的数据/文件会丢失的, 需要备份一下

**Comment by niubility6** [comment]
我试试

**Comment by niubility6** [comment]
System error [Failed to open a WebSocket connection. See server log for more information. ] in [/runman/api/websocket]
这个是为啥呀大佬

**Comment by rmb122** [comment]
参考这个 https://www.jianshu.com/p/8b81faca789b, 
```
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```
需要添加这个几个 proxy_header

**Comment by niubility6** [comment]
开发websocket是什么作用呀大佬，我发现的我的邮件发送失败，可能我用的香港服务器的原因吧

**Comment by rmb122** [comment]
websocket 是方便推送消息，就是 title 里面那个 [新消息]，不然的话得轮询实现比较浪费资源.
邮件发送失败 log 里面应该会有失败原因, 可以看看.

**Comment by niubility6** [comment]
恩 超时 应该是香港服务器原因

**Comment by niubility6** [comment]
按照你发的链接处理了，还是一样的报错websocket很奇怪

**Comment by niubility6** [comment]
解决好了。谢谢大佬

**Comment by niubility6** [comment]
本来以为是香港服务器的原因，换了一个邮件服务器还是不行，是否可能和我本地的反向代理有关呢？我给端口做了反向代理到域名

**Comment by niubility6** [comment]
都搞定了大佬，不过我记得以前的空白规则都能返回cookie呀

**Comment by rmb122** [comment]
空白规则返回 cookie 是什么意思, 能更详细的描述一下么
