### ISSUE TITLE
有办法记录下来ip的端口号吗？

### ISSUE THREAD

**Issue by niubility6** [rmb122/xss-receiver#7]
有办法记录下来ip的端口号吗？

**Comment by rmb122** [comment]
这个功能似乎意义不大? 能说一下使用场景么

**Comment by niubility6** [comment]
通过ip+端口号可以在运营商溯源，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rmb122/xss-receiver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月12日(星期四) 晚上10:48
***@***.***&gt;;
抄送:&nbsp;"ᵕ᷄≀ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [rmb122/xss-receiver] 有办法记录下来ip的端口号吗？ (Issue #7)





 
这个功能似乎意义不大? 能说一下使用场景么

**Comment by rmb122** [comment]
已增加此功能 https://github.com/rmb122/xss-receiver/commit/ceeed65551b4d10e90d85a8fbac6860d80a2dac2  

git pull + docker-compose restart 之后在数据库里面
`ALTER TABLE app.http_access_log ADD COLUMN client_port int(11) AFTER client_ip;`
就行了
